### ISSUE TITLE
Site occasionally not loading correctly

### ISSUE THREAD

**Issue by dwsilk** [foss4g-oceania/hoverboard#35] opened 2019-07-21 23:20 UTC
![Screen Shot 2019-07-22 at 10 22 47 AM](https://user-images.githubusercontent.com/8953184/61598482-aa9a5100-ac72-11e9-9366-5f68596adb96.png)

Possibly a race condition somewhere.

**Comment by hamishcampbell** [comment] 2019-07-22 00:21
Hey, I submitted this to Daniel, but I might be able to provide more info here.

  * Browser: FF 68.0
  * OS: macOS Mojave

This seems to happen more often on first load, and I've found it happening _consistently_ in private browsing:

![Screen Shot 2019-07-22 at 12 20 04 PM](https://user-images.githubusercontent.com/295074/61599236-108ad680-ac7b-11e9-8a72-85dac93328cc.png)

**Comment by hamishcampbell** [comment] 2019-07-22 00:23
Seems to be more frequent with dev tools open and cache disabled, hence speculation it's a race condition.

**Comment by alpha-beta-soup** [comment] 2019-07-30 08:22
Closed by #37

**Comment by alpha-beta-soup** [comment] 2019-07-30 08:23
@hamishcampbell Actually I should have asked before closing: can you please try reproduce again?

**Comment by hamishcampbell** [comment] 2019-07-31 00:51
Yep looking better now, thanks!

**Closed as completed** 2019-07-31 02:26 UTC
